# Generated by Django 3.1.2 on 2020-11-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FilmsApp', '0002_auto_20201113_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='fav',
            field=models.BooleanField(default=False),
        ),
    ]
